---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret-1
  namespace: workspace-1
type: Opaque
data:
  test: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret-2
  namespace: workspace-1
type: Opaque
data:
  test: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret-3
  namespace: workspace-1
type: Opaque
data:
  test: "true"
